# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rails db:seed command (or created alongside the database with db:setup).
#
# Examples:
#
#   movies = Movie.create([{ name: 'Star Wars' }, { name: 'Lord of the Rings' }])
#   Character.create(name: 'Luke', movie: movies.first)

dan = User.create(username: "dan", name: "Daniel Cole", email:"dantheman@gmail.com", password: "daniel", password_confirmation: "daniel")
will = User.create(username: "will", name: "William Stewart", email:"willshred4lyfe@gmail.com", password: "william", password_confirmation: "william")
sam = User.create(username: "sam", name: "Samuel Moseley", email:"trailsammich@gmail.com", password: "samuel", password_confirmation: "samuel")
# Bike.create( manufacturer: "", model: "", bike_type: "", size: "", build: "", price: , image: "", details: "")

Bike.create( manufacturer: "Specialized", model: "Epic", bike_type: "Cross Country", size: "S", build: "Pro 29", price: 7925 , image: "https://s7d5.scene7.com/is/image/Specialized/?$hybris-hd$&layer=0&fmt=jpg&src=is{Specialized/pdp-product-bg-dark-zoom?$hybris-hd$}&layer=1&src=is{Specialized/97620-31_EPIC-EXPERT-OIS-FSTGRN_HERO?$hybris-hd$}", details: "What do you get when you open up the taps on trickle-down technology? That'd be the Epic Pro. A waterfall of performance coming straight down from Mount S-Works, the Epic Pro benefits from the most efficient suspension design we've ever created, not to mention a frame that's as light as the previous-generation S-Works while offering the same incredibly efficient power transfer of the current cream of the World Cup crop.")
Bike.create( manufacturer: "Specialized", model: "Epic Hardtail", bike_type: "Cross Country", size: "S", build: "Pro", price: 5520, image: "https://s7d5.scene7.com/is/image/Specialized/?$hybris-hd$&layer=0&fmt=jpg&src=is{Specialized/pdp-product-bg-dark-zoom?$hybris-hd$}&layer=1&src=is{Specialized/91320-10_EPIC-HT-PRO-CARBON-29-VIVPNK-PROBLU-METWHTSIL_HERO?$hybris-hd$}", details: "If you ask us, it's been too long since hardtails got their world shaken up. Well, our all-new Epic Hardtail Pro Carbon does just that. New geometry, crazy-low frame weight, and a build from the racing gods—this bike is ready to shatter the mold.")
Bike.create( manufacturer: "Specialized", model: "Stumpjumper", bike_type: "Trail", size: "S", build: "Evo PRO 29", price: 5296 , image: "https://s7d5.scene7.com/is/image/Specialized/?$hybris-hd$&layer=0&fmt=jpg&src=is{Specialized/pdp-product-bg-dark-zoom?$hybris-hd$}&layer=1&src=is{Specialized/93319-11_SJ-FSR-MEN-PRO-CARBON-EVO-29-CARB-MNT_HERO?$hybris-hd$}", details: "If you're looking for a traditional trail bike, you've come to the wrong place. Pack your stuff, say your goodbyes, and get out. But if you're on the hunt for the perfect shred sled—you know, a trail bike that you can take down DH trails, huck off blind drops, or plow through the rowdiest of rock gardens—you'll find yourself right at home on the Stumpjumper EVO Pro 29.")
Bike.create( manufacturer: "Specialized", model: "Enduro", bike_type: "Enduro", size: "S", build: "S-Works", price: 9750 , image: "https://s7d5.scene7.com/is/image/Specialized/?$hybris-hd$&layer=0&fmt=jpg&src=is{Specialized/pdp-product-bg-dark-zoom?$hybris-hd$}&layer=1&src=is{Specialized/93620-00_ENDURO-SW-CARBON-29-BLKTNT-BRSHBLKCP-CARB_HERO?$hybris-hd$}", details: "This is the bike that defines the very genre that bears its name. The S-Works Enduro features a bomber-yet-lightweight carbon frame that blissfully tackles the kind of terrain that chews up and spits out lesser bikes. And it's absolutely dressed to kill. Let the drooling begin.")
Bike.create( manufacturer: "Specialized", model: "Demo", bike_type: "Downhill", size: "S", build: "Race 29", price: 6500 , image: "https://s7d5.scene7.com/is/image/Specialized/?$hybris-hd$&layer=0&fmt=jpg&src=is{Specialized/pdp-product-bg-dark-zoom?$hybris-hd$}&layer=1&src=is{Specialized/94519-00_DEMO_RACE-29_METBLK-BNTYEL_HERO?$hybris-hd$}", details: "The new Demo 29 comes roaring comes roaring out of the gates with multiple World Cup wins already under its belt. New chassis, new suspension kinematics, new geometry, and, yeah, new wheel size. We’ve hung the Race model with the best gravity kit available. Full gas. Full fast.")
Bike.create( manufacturer: "Specialized", model: "Diverge", bike_type: "Gravel", size: "S", build: "Pro Carbon", price: 6700 , image: "https://s7d5.scene7.com/is/image/Specialized/?$hybris-hd$&layer=0&fmt=jpg&src=is{Specialized/pdp-product-bg-dark-zoom?$hybris-hd$}&layer=1&src=is{Specialized/96220-10_DIVERGE-PRO-CARBON-ETAP-REDWD-SMK-CHRM_HERO?$hybris-hd$}", details: "Whether your goal is to escape on gravel back roads, far from cars and crowds, or drop the hammer at the front of your favorite gravel race, no bike does it better than the new Diverge. It’s quite simply the fastest, most capable - and just maybe the most fun - bike we’ve ever made, delivering a ride that’s quick and lively under power, but stable and confidence inspiring when the terrain gets rough.")

Bike.create( manufacturer: "Specialized", model: "Epic", bike_type: "Cross Country", size: "M", build: "Pro 29", price: 7925 , image: "https://s7d5.scene7.com/is/image/Specialized/?$hybris-hd$&layer=0&fmt=jpg&src=is{Specialized/pdp-product-bg-dark-zoom?$hybris-hd$}&layer=1&src=is{Specialized/97620-31_EPIC-EXPERT-OIS-FSTGRN_HERO?$hybris-hd$}", details: "What do you get when you open up the taps on trickle-down technology? That'd be the Epic Pro. A waterfall of performance coming straight down from Mount S-Works, the Epic Pro benefits from the most efficient suspension design we've ever created, not to mention a frame that's as light as the previous-generation S-Works while offering the same incredibly efficient power transfer of the current cream of the World Cup crop.")
Bike.create( manufacturer: "Specialized", model: "Epic Hardtail", bike_type: "Cross Country", size: "S", build: "Pro", price: 5520, image: "https://s7d5.scene7.com/is/image/Specialized/?$hybris-hd$&layer=0&fmt=jpg&src=is{Specialized/pdp-product-bg-dark-zoom?$hybris-hd$}&layer=1&src=is{Specialized/91320-10_EPIC-HT-PRO-CARBON-29-VIVPNK-PROBLU-METWHTSIL_HERO?$hybris-hd$}", details: "If you ask us, it's been too long since hardtails got their world shaken up. Well, our all-new Epic Hardtail Pro Carbon does just that. New geometry, crazy-low frame weight, and a build from the racing gods—this bike is ready to shatter the mold.")
Bike.create( manufacturer: "Specialized", model: "Stumpjumper", bike_type: "Trail", size: "M", build: "Evo PRO 29", price: 5296 , image: "https://s7d5.scene7.com/is/image/Specialized/?$hybris-hd$&layer=0&fmt=jpg&src=is{Specialized/pdp-product-bg-dark-zoom?$hybris-hd$}&layer=1&src=is{Specialized/93319-11_SJ-FSR-MEN-PRO-CARBON-EVO-29-CARB-MNT_HERO?$hybris-hd$}", details: "If you're looking for a traditional trail bike, you've come to the wrong place. Pack your stuff, say your goodbyes, and get out. But if you're on the hunt for the perfect shred sled—you know, a trail bike that you can take down DH trails, huck off blind drops, or plow through the rowdiest of rock gardens—you'll find yourself right at home on the Stumpjumper EVO Pro 29.")
Bike.create( manufacturer: "Specialized", model: "Enduro", bike_type: "Enduro", size: "M", build: "S-Works", price: 9750 , image: "https://s7d5.scene7.com/is/image/Specialized/?$hybris-hd$&layer=0&fmt=jpg&src=is{Specialized/pdp-product-bg-dark-zoom?$hybris-hd$}&layer=1&src=is{Specialized/93620-00_ENDURO-SW-CARBON-29-BLKTNT-BRSHBLKCP-CARB_HERO?$hybris-hd$}", details: "This is the bike that defines the very genre that bears its name. The S-Works Enduro features a bomber-yet-lightweight carbon frame that blissfully tackles the kind of terrain that chews up and spits out lesser bikes. And it's absolutely dressed to kill. Let the drooling begin.")
Bike.create( manufacturer: "Specialized", model: "Demo", bike_type: "Downhill", size: "M", build: "Race 29", price: 6500 , image: "https://s7d5.scene7.com/is/image/Specialized/?$hybris-hd$&layer=0&fmt=jpg&src=is{Specialized/pdp-product-bg-dark-zoom?$hybris-hd$}&layer=1&src=is{Specialized/94519-00_DEMO_RACE-29_METBLK-BNTYEL_HERO?$hybris-hd$}", details: "The new Demo 29 comes roaring comes roaring out of the gates with multiple World Cup wins already under its belt. New chassis, new suspension kinematics, new geometry, and, yeah, new wheel size. We’ve hung the Race model with the best gravity kit available. Full gas. Full fast.")
Bike.create( manufacturer: "Specialized", model: "Diverge", bike_type: "Gravel", size: "M", build: "Pro Carbon", price: 6700 , image: "https://s7d5.scene7.com/is/image/Specialized/?$hybris-hd$&layer=0&fmt=jpg&src=is{Specialized/pdp-product-bg-dark-zoom?$hybris-hd$}&layer=1&src=is{Specialized/96220-10_DIVERGE-PRO-CARBON-ETAP-REDWD-SMK-CHRM_HERO?$hybris-hd$}", details: "Whether your goal is to escape on gravel back roads, far from cars and crowds, or drop the hammer at the front of your favorite gravel race, no bike does it better than the new Diverge. It’s quite simply the fastest, most capable - and just maybe the most fun - bike we’ve ever made, delivering a ride that’s quick and lively under power, but stable and confidence inspiring when the terrain gets rough.")

Bike.create( manufacturer: "Specialized", model: "Epic", bike_type: "Cross Country", size: "L", build: "Pro 29", price: 7925 , image: "https://s7d5.scene7.com/is/image/Specialized/?$hybris-hd$&layer=0&fmt=jpg&src=is{Specialized/pdp-product-bg-dark-zoom?$hybris-hd$}&layer=1&src=is{Specialized/97620-31_EPIC-EXPERT-OIS-FSTGRN_HERO?$hybris-hd$}", details: "What do you get when you open up the taps on trickle-down technology? That'd be the Epic Pro. A waterfall of performance coming straight down from Mount S-Works, the Epic Pro benefits from the most efficient suspension design we've ever created, not to mention a frame that's as light as the previous-generation S-Works while offering the same incredibly efficient power transfer of the current cream of the World Cup crop.")
Bike.create( manufacturer: "Specialized", model: "Epic Hardtail", bike_type: "Cross Country", size: "L", build: "Pro", price: 5520, image: "https://s7d5.scene7.com/is/image/Specialized/?$hybris-hd$&layer=0&fmt=jpg&src=is{Specialized/pdp-product-bg-dark-zoom?$hybris-hd$}&layer=1&src=is{Specialized/91320-10_EPIC-HT-PRO-CARBON-29-VIVPNK-PROBLU-METWHTSIL_HERO?$hybris-hd$}", details: "If you ask us, it's been too long since hardtails got their world shaken up. Well, our all-new Epic Hardtail Pro Carbon does just that. New geometry, crazy-low frame weight, and a build from the racing gods—this bike is ready to shatter the mold.")
Bike.create( manufacturer: "Specialized", model: "Stumpjumper", bike_type: "Trail", size: "L", build: "Evo PRO 29", price: 5296 , image: "https://s7d5.scene7.com/is/image/Specialized/?$hybris-hd$&layer=0&fmt=jpg&src=is{Specialized/pdp-product-bg-dark-zoom?$hybris-hd$}&layer=1&src=is{Specialized/93319-11_SJ-FSR-MEN-PRO-CARBON-EVO-29-CARB-MNT_HERO?$hybris-hd$}", details: "If you're looking for a traditional trail bike, you've come to the wrong place. Pack your stuff, say your goodbyes, and get out. But if you're on the hunt for the perfect shred sled—you know, a trail bike that you can take down DH trails, huck off blind drops, or plow through the rowdiest of rock gardens—you'll find yourself right at home on the Stumpjumper EVO Pro 29.")
Bike.create( manufacturer: "Specialized", model: "Enduro", bike_type: "Enduro", size: "L", build: "S-Works", price: 9750 , image: "https://s7d5.scene7.com/is/image/Specialized/?$hybris-hd$&layer=0&fmt=jpg&src=is{Specialized/pdp-product-bg-dark-zoom?$hybris-hd$}&layer=1&src=is{Specialized/93620-00_ENDURO-SW-CARBON-29-BLKTNT-BRSHBLKCP-CARB_HERO?$hybris-hd$}", details: "This is the bike that defines the very genre that bears its name. The S-Works Enduro features a bomber-yet-lightweight carbon frame that blissfully tackles the kind of terrain that chews up and spits out lesser bikes. And it's absolutely dressed to kill. Let the drooling begin.")
Bike.create( manufacturer: "Specialized", model: "Demo", bike_type: "Downhill", size: "L", build: "Race 29", price: 6500 , image: "https://s7d5.scene7.com/is/image/Specialized/?$hybris-hd$&layer=0&fmt=jpg&src=is{Specialized/pdp-product-bg-dark-zoom?$hybris-hd$}&layer=1&src=is{Specialized/94519-00_DEMO_RACE-29_METBLK-BNTYEL_HERO?$hybris-hd$}", details: "The new Demo 29 comes roaring comes roaring out of the gates with multiple World Cup wins already under its belt. New chassis, new suspension kinematics, new geometry, and, yeah, new wheel size. We’ve hung the Race model with the best gravity kit available. Full gas. Full fast.")
Bike.create( manufacturer: "Specialized", model: "Diverge", bike_type: "Gravel", size: "L", build: "Pro Carbon", price: 6700 , image: "https://s7d5.scene7.com/is/image/Specialized/?$hybris-hd$&layer=0&fmt=jpg&src=is{Specialized/pdp-product-bg-dark-zoom?$hybris-hd$}&layer=1&src=is{Specialized/96220-10_DIVERGE-PRO-CARBON-ETAP-REDWD-SMK-CHRM_HERO?$hybris-hd$}", details: "Whether your goal is to escape on gravel back roads, far from cars and crowds, or drop the hammer at the front of your favorite gravel race, no bike does it better than the new Diverge. It’s quite simply the fastest, most capable - and just maybe the most fun - bike we’ve ever made, delivering a ride that’s quick and lively under power, but stable and confidence inspiring when the terrain gets rough.")

Bike.create( manufacturer: "Specialized", model: "Epic", bike_type: "Cross Country", size: "XL", build: "Pro 29", price: 7925 , image: "https://s7d5.scene7.com/is/image/Specialized/?$hybris-hd$&layer=0&fmt=jpg&src=is{Specialized/pdp-product-bg-dark-zoom?$hybris-hd$}&layer=1&src=is{Specialized/97620-31_EPIC-EXPERT-OIS-FSTGRN_HERO?$hybris-hd$}", details: "What do you get when you open up the taps on trickle-down technology? That'd be the Epic Pro. A waterfall of performance coming straight down from Mount S-Works, the Epic Pro benefits from the most efficient suspension design we've ever created, not to mention a frame that's as light as the previous-generation S-Works while offering the same incredibly efficient power transfer of the current cream of the World Cup crop.")
Bike.create( manufacturer: "Specialized", model: "Epic Hardtail", bike_type: "Cross Country", size: "XL", build: "Pro", price: 5520, image: "https://s7d5.scene7.com/is/image/Specialized/?$hybris-hd$&layer=0&fmt=jpg&src=is{Specialized/pdp-product-bg-dark-zoom?$hybris-hd$}&layer=1&src=is{Specialized/91320-10_EPIC-HT-PRO-CARBON-29-VIVPNK-PROBLU-METWHTSIL_HERO?$hybris-hd$}", details: "If you ask us, it's been too long since hardtails got their world shaken up. Well, our all-new Epic Hardtail Pro Carbon does just that. New geometry, crazy-low frame weight, and a build from the racing gods—this bike is ready to shatter the mold.")
Bike.create( manufacturer: "Specialized", model: "Stumpjumper", bike_type: "Trail", size: "XL", build: "Evo PRO 29", price: 5296 , image: "https://s7d5.scene7.com/is/image/Specialized/?$hybris-hd$&layer=0&fmt=jpg&src=is{Specialized/pdp-product-bg-dark-zoom?$hybris-hd$}&layer=1&src=is{Specialized/93319-11_SJ-FSR-MEN-PRO-CARBON-EVO-29-CARB-MNT_HERO?$hybris-hd$}", details: "If you're looking for a traditional trail bike, you've come to the wrong place. Pack your stuff, say your goodbyes, and get out. But if you're on the hunt for the perfect shred sled—you know, a trail bike that you can take down DH trails, huck off blind drops, or plow through the rowdiest of rock gardens—you'll find yourself right at home on the Stumpjumper EVO Pro 29.")
Bike.create( manufacturer: "Specialized", model: "Enduro", bike_type: "Enduro", size: "L", build: "S-Works", price: 9750 , image: "https://s7d5.scene7.com/is/image/Specialized/?$hybris-hd$&layer=0&fmt=jpg&src=is{Specialized/pdp-product-bg-dark-zoom?$hybris-hd$}&layer=1&src=is{Specialized/93620-00_ENDURO-SW-CARBON-29-BLKTNT-BRSHBLKCP-CARB_HERO?$hybris-hd$}", details: "This is the bike that defines the very genre that bears its name. The S-Works Enduro features a bomber-yet-lightweight carbon frame that blissfully tackles the kind of terrain that chews up and spits out lesser bikes. And it's absolutely dressed to kill. Let the drooling begin.")
Bike.create( manufacturer: "Specialized", model: "Demo", bike_type: "Downhill", size: "XL", build: "Race 29", price: 6500 , image: "https://s7d5.scene7.com/is/image/Specialized/?$hybris-hd$&layer=0&fmt=jpg&src=is{Specialized/pdp-product-bg-dark-zoom?$hybris-hd$}&layer=1&src=is{Specialized/94519-00_DEMO_RACE-29_METBLK-BNTYEL_HERO?$hybris-hd$}", details: "The new Demo 29 comes roaring comes roaring out of the gates with multiple World Cup wins already under its belt. New chassis, new suspension kinematics, new geometry, and, yeah, new wheel size. We’ve hung the Race model with the best gravity kit available. Full gas. Full fast.")
Bike.create( manufacturer: "Specialized", model: "Diverge", bike_type: "Gravel", size: "XL", build: "Pro Carbon", price: 6700 , image: "https://s7d5.scene7.com/is/image/Specialized/?$hybris-hd$&layer=0&fmt=jpg&src=is{Specialized/pdp-product-bg-dark-zoom?$hybris-hd$}&layer=1&src=is{Specialized/96220-10_DIVERGE-PRO-CARBON-ETAP-REDWD-SMK-CHRM_HERO?$hybris-hd$}", details: "Whether your goal is to escape on gravel back roads, far from cars and crowds, or drop the hammer at the front of your favorite gravel race, no bike does it better than the new Diverge. It’s quite simply the fastest, most capable - and just maybe the most fun - bike we’ve ever made, delivering a ride that’s quick and lively under power, but stable and confidence inspiring when the terrain gets rough.")


Bike.create( manufacturer: "Santa Cruz", model: "Blur", bike_type: "Cross Country", size: "S", build: "Carbon CC - X01 - 29", price: 7699 , image: "https://www.santacruzbicycles.com/files/styles/scb_natural_2000_auto/public/hero/my21_hero_blur_black.jpg?itok=c3bIFnAQ", details: "The Blur is our ride fast, ride far, ride-harder-than-your-heart-can-take XC race bike. Light enough to scorch hot laps and tough enough to endure a long-distance beating, the Blur does it all without compromise. No matter how demanding your next XC endeavor, the Blur is ready to go full gas, 24/7.")
Bike.create( manufacturer: "Santa Cruz", model: "5010", bike_type: "Trail", size: "S", build: "Carbon CC - X01 - 27.5", price: 8099, image: "https://www.santacruzbicycles.com/files/styles/scb_natural_2000_auto/public/hero/my21_hero_5010_blue.jpg?itok=vO9hFHbj", details: "The 5010 turns obstacles into features. Its nimble, poppy feel makes even the most mundane rides feel like they're loaded with features to hop, skip and jump over. It's the kind of bike that makes new trails feel as familiar as the back of your hand.")
Bike.create( manufacturer: "Santa Cruz", model: "Bronson", bike_type: "Enduro", size: "S", build: "Carbon CC - X01 - 27.5", price: 8299, image: "https://www.santacruzbicycles.com/files/styles/scb_natural_2000_auto/public/hero/my21_hero_bronson_green.jpg?itok=h2nTgVbG", details: "Santa Cruz's most notorious thriller, the Bronson, is ready for action no matter what role it's cast into. The Bronson has the biggest personality in our range. From flat out on the trail to fully flat over a table, each new generation redefines expectations of what a 150mm bike can do.")
Bike.create( manufacturer: "Santa Cruz", model: "V-10", bike_type: "Downhill", size: "S", build: "Carbon CC - X01 - 27.5", price: 7999, image: "https://www.santacruzbicycles.com/files/styles/scb_natural_2000_auto/public/hero/my21_hero_v10_mx.jpg?itok=dWA3411A", details: "The V10 is designed to be exactly the right bike for anyone who steps up to the startline with eyes on a podium. The racer who chooses a V10 is the recipient of every bit of work and puzzling that’s gone into the Syndicate’s race bikes.")
Bike.create( manufacturer: "Santa Cruz", model: "Stigmata", bike_type: "Gravel", size: "S", build: "Carbon CC - Force 1X - 700c", price: 6699, image: "https://www.santacruzbicycles.com/files/styles/scb_natural_2000_auto/public/hero/my21_hero_stig_green.jpg?itok=d1HO2YC6", details: "When the Stigmata was resurrected in 2015, we fused a number of MTB standards and design features to create our spin on the modern CX bike. Something must have clicked, because within months of launch it raced to victory at the legendary Three Peaks, and has continued to contend at elite cyclocross races around the world.")

Bike.create( manufacturer: "Santa Cruz", model: "Blur", bike_type: "Cross Country", size: "M", build: "Carbon CC - X01 - 29", price: 7699 , image: "https://www.santacruzbicycles.com/files/styles/scb_natural_2000_auto/public/hero/my21_hero_blur_black.jpg?itok=c3bIFnAQ", details: "The Blur is our ride fast, ride far, ride-harder-than-your-heart-can-take XC race bike. Light enough to scorch hot laps and tough enough to endure a long-distance beating, the Blur does it all without compromise. No matter how demanding your next XC endeavor, the Blur is ready to go full gas, 24/7.")
Bike.create( manufacturer: "Santa Cruz", model: "5010", bike_type: "Trail", size: "M", build: "Carbon CC - X01 - 27.5", price: 8099, image: "https://www.santacruzbicycles.com/files/styles/scb_natural_2000_auto/public/hero/my21_hero_5010_blue.jpg?itok=vO9hFHbj", details: "The 5010 turns obstacles into features. Its nimble, poppy feel makes even the most mundane rides feel like they're loaded with features to hop, skip and jump over. It's the kind of bike that makes new trails feel as familiar as the back of your hand.")
Bike.create( manufacturer: "Santa Cruz", model: "Bronson", bike_type: "Enduro", size: "M", build: "Carbon CC - X01 - 27.5", price: 8299, image: "https://www.santacruzbicycles.com/files/styles/scb_natural_2000_auto/public/hero/my21_hero_bronson_green.jpg?itok=h2nTgVbG", details: "Santa Cruz's most notorious thriller, the Bronson, is ready for action no matter what role it's cast into. The Bronson has the biggest personality in our range. From flat out on the trail to fully flat over a table, each new generation redefines expectations of what a 150mm bike can do.")
Bike.create( manufacturer: "Santa Cruz", model: "V-10", bike_type: "Downhill", size: "M", build: "Carbon CC - X01 - 27.5", price: 7999, image: "https://www.santacruzbicycles.com/files/styles/scb_natural_2000_auto/public/hero/my21_hero_v10_mx.jpg?itok=dWA3411A", details: "The V10 is designed to be exactly the right bike for anyone who steps up to the startline with eyes on a podium. The racer who chooses a V10 is the recipient of every bit of work and puzzling that’s gone into the Syndicate’s race bikes.")
Bike.create( manufacturer: "Santa Cruz", model: "Stigmata", bike_type: "Gravel", size: "M", build: "Carbon CC - Force 1X - 700c", price: 6699, image: "https://www.santacruzbicycles.com/files/styles/scb_natural_2000_auto/public/hero/my21_hero_stig_green.jpg?itok=d1HO2YC6", details: "When the Stigmata was resurrected in 2015, we fused a number of MTB standards and design features to create our spin on the modern CX bike. Something must have clicked, because within months of launch it raced to victory at the legendary Three Peaks, and has continued to contend at elite cyclocross races around the world.")

Bike.create( manufacturer: "Santa Cruz", model: "Blur", bike_type: "Cross Country", size: "L", build: "Carbon CC - X01 - 29", price: 7699 , image: "https://www.santacruzbicycles.com/files/styles/scb_natural_2000_auto/public/hero/my21_hero_blur_black.jpg?itok=c3bIFnAQ", details: "The Blur is our ride fast, ride far, ride-harder-than-your-heart-can-take XC race bike. Light enough to scorch hot laps and tough enough to endure a long-distance beating, the Blur does it all without compromise. No matter how demanding your next XC endeavor, the Blur is ready to go full gas, 24/7.")
Bike.create( manufacturer: "Santa Cruz", model: "5010", bike_type: "Trail", size: "L", build: "Carbon CC - X01 - 27.5", price: 8099, image: "https://www.santacruzbicycles.com/files/styles/scb_natural_2000_auto/public/hero/my21_hero_5010_blue.jpg?itok=vO9hFHbj", details: "The 5010 turns obstacles into features. Its nimble, poppy feel makes even the most mundane rides feel like they're loaded with features to hop, skip and jump over. It's the kind of bike that makes new trails feel as familiar as the back of your hand.")
bronsonL = Bike.create( manufacturer: "Santa Cruz", model: "Bronson", bike_type: "Enduro", size: "L", build: "Carbon CC - X01 - 27.5", price: 8299, image: "https://www.santacruzbicycles.com/files/styles/scb_natural_2000_auto/public/hero/my21_hero_bronson_green.jpg?itok=h2nTgVbG", details: "Santa Cruz's most notorious thriller, the Bronson, is ready for action no matter what role it's cast into. The Bronson has the biggest personality in our range. From flat out on the trail to fully flat over a table, each new generation redefines expectations of what a 150mm bike can do.")
veetenL = Bike.create( manufacturer: "Santa Cruz", model: "V-10", bike_type: "Downhill", size: "L", build: "Carbon CC - X01 - 27.5", price: 7999, image: "https://www.santacruzbicycles.com/files/styles/scb_natural_2000_auto/public/hero/my21_hero_v10_mx.jpg?itok=dWA3411A", details: "The V10 is designed to be exactly the right bike for anyone who steps up to the startline with eyes on a podium. The racer who chooses a V10 is the recipient of every bit of work and puzzling that’s gone into the Syndicate’s race bikes.")
stigmataL = Bike.create( manufacturer: "Santa Cruz", model: "Stigmata", bike_type: "Gravel", size: "L", build: "Carbon CC - Force 1X - 700c", price: 6699, image: "https://www.santacruzbicycles.com/files/styles/scb_natural_2000_auto/public/hero/my21_hero_stig_green.jpg?itok=d1HO2YC6", details: "When the Stigmata was resurrected in 2015, we fused a number of MTB standards and design features to create our spin on the modern CX bike. Something must have clicked, because within months of launch it raced to victory at the legendary Three Peaks, and has continued to contend at elite cyclocross races around the world.")

Bike.create( manufacturer: "Santa Cruz", model: "Blur", bike_type: "Cross Country", size: "XL", build: "Carbon CC - X01 - 29", price: 7699 , image: "https://www.santacruzbicycles.com/files/styles/scb_natural_2000_auto/public/hero/my21_hero_blur_black.jpg?itok=c3bIFnAQ", details: "The Blur is our ride fast, ride far, ride-harder-than-your-heart-can-take XC race bike. Light enough to scorch hot laps and tough enough to endure a long-distance beating, the Blur does it all without compromise. No matter how demanding your next XC endeavor, the Blur is ready to go full gas, 24/7.")
Bike.create( manufacturer: "Santa Cruz", model: "5010", bike_type: "Trail", size: "XL", build: "Carbon CC - X01 - 27.5", price: 8099, image: "https://www.santacruzbicycles.com/files/styles/scb_natural_2000_auto/public/hero/my21_hero_5010_blue.jpg?itok=vO9hFHbj", details: "The 5010 turns obstacles into features. Its nimble, poppy feel makes even the most mundane rides feel like they're loaded with features to hop, skip and jump over. It's the kind of bike that makes new trails feel as familiar as the back of your hand.")
Bike.create( manufacturer: "Santa Cruz", model: "Bronson", bike_type: "Enduro", size: "XL", build: "Carbon CC - X01 - 27.5", price: 8299, image: "https://www.santacruzbicycles.com/files/styles/scb_natural_2000_auto/public/hero/my21_hero_bronson_green.jpg?itok=h2nTgVbG", details: "Santa Cruz's most notorious thriller, the Bronson, is ready for action no matter what role it's cast into. The Bronson has the biggest personality in our range. From flat out on the trail to fully flat over a table, each new generation redefines expectations of what a 150mm bike can do.")
veetenXL = Bike.create( manufacturer: "Santa Cruz", model: "V-10", bike_type: "Downhill", size: "XL", build: "Carbon CC - X01 - 27.5", price: 7999, image: "https://www.santacruzbicycles.com/files/styles/scb_natural_2000_auto/public/hero/my21_hero_v10_mx.jpg?itok=dWA3411A", details: "The V10 is designed to be exactly the right bike for anyone who steps up to the startline with eyes on a podium. The racer who chooses a V10 is the recipient of every bit of work and puzzling that’s gone into the Syndicate’s race bikes.")
Bike.create( manufacturer: "Santa Cruz", model: "Stigmata", bike_type: "Gravel", size: "XL", build: "Carbon CC - Force 1X - 700c", price: 6699, image: "https://www.santacruzbicycles.com/files/styles/scb_natural_2000_auto/public/hero/my21_hero_stig_green.jpg?itok=d1HO2YC6", details: "When the Stigmata was resurrected in 2015, we fused a number of MTB standards and design features to create our spin on the modern CX bike. Something must have clicked, because within months of launch it raced to victory at the legendary Three Peaks, and has continued to contend at elite cyclocross races around the world.")

o1 = Order.create(user_id: dan.id, order_total: 16298)
o2 = Order.create(user_id: dan.id, order_total: 6699)
o3 = Order.create(user_id: will.id, order_total: 7999)
o1.bikes << bronsonL
o1.bikes << veetenL
o2.bikes << stigmataL
o3.bikes << veetenXL

Bike.create( manufacturer: "Ibis", model: "MOJO HD5", bike_type: "Enduro", size: "S", build: "SLX", price: 5199 , image: "https://content.backcountry.com/images/items/900/IBS/IBSB065/BLA.jpg", details: "Enduro World Series tested and team-approved, the HD5 lives for ragged descents combined with real-world climbs requiring efficiency, positioning and poise. Which it delivers in spades. It’s the ultimate 27.5in brawler, living to ride as hard up as down with 153mm of dw-link controlled travel and a 170mm fork. 76 degrees of climbing we would like you to meet 64 degrees of descending.")
Bike.create( manufacturer: "Ibis", model: "MOJO HD5", bike_type: "Enduro", size: "M", build: "SLX", price: 5199 , image: "https://content.backcountry.com/images/items/900/IBS/IBSB065/BLA.jpg", details: "Enduro World Series tested and team-approved, the HD5 lives for ragged descents combined with real-world climbs requiring efficiency, positioning and poise. Which it delivers in spades. It’s the ultimate 27.5in brawler, living to ride as hard up as down with 153mm of dw-link controlled travel and a 170mm fork. 76 degrees of climbing we would like you to meet 64 degrees of descending.")
Bike.create( manufacturer: "Ibis", model: "MOJO HD5", bike_type: "Enduro", size: "L", build: "SLX", price: 5199 , image: "https://content.backcountry.com/images/items/900/IBS/IBSB065/BLA.jpg", details: "Enduro World Series tested and team-approved, the HD5 lives for ragged descents combined with real-world climbs requiring efficiency, positioning and poise. Which it delivers in spades. It’s the ultimate 27.5in brawler, living to ride as hard up as down with 153mm of dw-link controlled travel and a 170mm fork. 76 degrees of climbing we would like you to meet 64 degrees of descending.")
Bike.create( manufacturer: "Ibis", model: "MOJO HD5", bike_type: "Enduro", size: "XL", build: "SLX", price: 5199 , image: "https://content.backcountry.com/images/items/900/IBS/IBSB065/BLA.jpg", details: "Enduro World Series tested and team-approved, the HD5 lives for ragged descents combined with real-world climbs requiring efficiency, positioning and poise. Which it delivers in spades. It’s the ultimate 27.5in brawler, living to ride as hard up as down with 153mm of dw-link controlled travel and a 170mm fork. 76 degrees of climbing we would like you to meet 64 degrees of descending.")

Bike.create( manufacturer: "Ibis", model: "Ripley", bike_type: "Trail", size: "S", build: "Deore", price: 4199 , image: "https://content.backcountry.com/images/items/900/IBS/IBSB06S/BLUSTE.jpg", details: "The Ripley is our snappy, flickable, playful, fast, lightweight, and versatile 29in trail bike. Its combination of modern geometry, a stiff lightweight carbon chassis, and 120mm of ultra efficient dw-link travel, means it’s equally happy popping off bonus lines as it is crushing all day epics.")
Bike.create( manufacturer: "Ibis", model: "Ripley", bike_type: "Trail", size: "M", build: "Deore", price: 4199 , image: "https://content.backcountry.com/images/items/900/IBS/IBSB06S/BLUSTE.jpg", details: "The Ripley is our snappy, flickable, playful, fast, lightweight, and versatile 29in trail bike. Its combination of modern geometry, a stiff lightweight carbon chassis, and 120mm of ultra efficient dw-link travel, means it’s equally happy popping off bonus lines as it is crushing all day epics.")
Bike.create( manufacturer: "Ibis", model: "Ripley", bike_type: "Trail", size: "L", build: "Deore", price: 4199 , image: "https://content.backcountry.com/images/items/900/IBS/IBSB06S/BLUSTE.jpg", details: "The Ripley is our snappy, flickable, playful, fast, lightweight, and versatile 29in trail bike. Its combination of modern geometry, a stiff lightweight carbon chassis, and 120mm of ultra efficient dw-link travel, means it’s equally happy popping off bonus lines as it is crushing all day epics.")
Bike.create( manufacturer: "Ibis", model: "Ripley", bike_type: "Trail", size: "XL", build: "Deore", price: 4199 , image: "https://content.backcountry.com/images/items/900/IBS/IBSB06S/BLUSTE.jpg", details: "The Ripley is our snappy, flickable, playful, fast, lightweight, and versatile 29in trail bike. Its combination of modern geometry, a stiff lightweight carbon chassis, and 120mm of ultra efficient dw-link travel, means it’s equally happy popping off bonus lines as it is crushing all day epics.")

Bike.create( manufacturer: "Ibis", model: "Hakka MX", bike_type: "Gravel", size: "S", build: "700c Rival 1", price: 3399, image: "https://content.backcountry.com/images/items/900/IBS/IBSB05X/FIR.jpg", details: "The Hakka MX is our answer to the Swiss Army Knife.")
Bike.create( manufacturer: "Ibis", model: "Hakka MX", bike_type: "Gravel", size: "M", build: "700c Rival 1", price: 3399, image: "https://content.backcountry.com/images/items/900/IBS/IBSB05X/FIR.jpg", details: "The Hakka MX is our answer to the Swiss Army Knife.")
Bike.create( manufacturer: "Ibis", model: "Hakka MX", bike_type: "Gravel", size: "L", build: "700c Rival 1", price: 3399, image: "https://content.backcountry.com/images/items/900/IBS/IBSB05X/FIR.jpg", details: "The Hakka MX is our answer to the Swiss Army Knife.")
Bike.create( manufacturer: "Ibis", model: "Hakka MX", bike_type: "Gravel", size: "XL", build: "700c Rival 1", price: 3399, image: "https://content.backcountry.com/images/items/900/IBS/IBSB05X/FIR.jpg", details: "The Hakka MX is our answer to the Swiss Army Knife.")

Bike.create( manufacturer: "Ibis", model: "Hakka MX", bike_type: "Gravel", size: "S", build: "650b GRX", price: 4399, image: "https://content.backcountry.com/images/items/900/IBS/IBSB05X/COA.jpg", details: "The Hakka MX is our answer to the Swiss Army Knife.")
Bike.create( manufacturer: "Ibis", model: "Hakka MX", bike_type: "Gravel", size: "M", build: "650b GRX", price: 4399, image: "https://content.backcountry.com/images/items/900/IBS/IBSB05X/COA.jpg", details: "The Hakka MX is our answer to the Swiss Army Knife.")
Bike.create( manufacturer: "Ibis", model: "Hakka MX", bike_type: "Gravel", size: "L", build: "650b GRX", price: 4399, image: "https://content.backcountry.com/images/items/900/IBS/IBSB05X/COA.jpg", details: "The Hakka MX is our answer to the Swiss Army Knife.")
Bike.create( manufacturer: "Ibis", model: "Hakka MX", bike_type: "Gravel", size: "XL", build: "650b GRX", price: 4399, image: "https://content.backcountry.com/images/items/900/IBS/IBSB05X/COA.jpg", details: "The Hakka MX is our answer to the Swiss Army Knife.")


Bike.create( manufacturer: "Pivot Cycles", model: "Phoenix 29", bike_type: "Downhill", size: "S", build: "Bernard Kerr Edition", price: 9199 , image: "https://store.pivotcycles.com/content/images/thumbs/0017958_phoenix-29.png", details: "Few riders go bigger or ride harder than Bernard Kerr, with a King of Crankworx title and two Redbull Hardline wins to prove it. The Bernard Kerr Collector’s Edition Phoenix 29 celebrates a decade of DH development: it is a bike born of Bernard's speed, all-out style, and penchant for pushing the limits on a Pivot.")
Bike.create( manufacturer: "Pivot Cycles", model: "Phoenix 29", bike_type: "Downhill", size: "M", build: "Bernard Kerr Edition", price: 9199 , image: "https://store.pivotcycles.com/content/images/thumbs/0017958_phoenix-29.png", details: "Few riders go bigger or ride harder than Bernard Kerr, with a King of Crankworx title and two Redbull Hardline wins to prove it. The Bernard Kerr Collector’s Edition Phoenix 29 celebrates a decade of DH development: it is a bike born of Bernard's speed, all-out style, and penchant for pushing the limits on a Pivot.")
Bike.create( manufacturer: "Pivot Cycles", model: "Phoenix 29", bike_type: "Downhill", size: "L", build: "Bernard Kerr Edition", price: 9199 , image: "https://store.pivotcycles.com/content/images/thumbs/0017958_phoenix-29.png", details: "Few riders go bigger or ride harder than Bernard Kerr, with a King of Crankworx title and two Redbull Hardline wins to prove it. The Bernard Kerr Collector’s Edition Phoenix 29 celebrates a decade of DH development: it is a bike born of Bernard's speed, all-out style, and penchant for pushing the limits on a Pivot.")
Bike.create( manufacturer: "Pivot Cycles", model: "Phoenix 29", bike_type: "Downhill", size: "XL", build: "Bernard Kerr Edition", price: 9199 , image: "https://store.pivotcycles.com/content/images/thumbs/0017958_phoenix-29.png", details: "Few riders go bigger or ride harder than Bernard Kerr, with a King of Crankworx title and two Redbull Hardline wins to prove it. The Bernard Kerr Collector’s Edition Phoenix 29 celebrates a decade of DH development: it is a bike born of Bernard's speed, all-out style, and penchant for pushing the limits on a Pivot.")

Bike.create( manufacturer: "Pivot Cycles", model: "Switchblade", bike_type: "Enduro", size: "S", build: "Race XT", price: 5499 , image: "https://store.pivotcycles.com/content/images/thumbs/0016340_switchblade.png", details: "The sequel to the Switchblade story heralds a new era of all mountain riding, with more travel, unrivaled versatility and progressive geometry. It unleashes dominance over enduro inspired descents, generates speed, and delivers the finesse needed for power moves on technical climbs. With a masterfully designed new dw-link shock layout, riders can optimize suspension performance like never before.")
Bike.create( manufacturer: "Pivot Cycles", model: "Switchblade", bike_type: "Enduro", size: "M", build: "Race XT", price: 5499 , image: "https://store.pivotcycles.com/content/images/thumbs/0016340_switchblade.png", details: "The sequel to the Switchblade story heralds a new era of all mountain riding, with more travel, unrivaled versatility and progressive geometry. It unleashes dominance over enduro inspired descents, generates speed, and delivers the finesse needed for power moves on technical climbs. With a masterfully designed new dw-link shock layout, riders can optimize suspension performance like never before.")
Bike.create( manufacturer: "Pivot Cycles", model: "Switchblade", bike_type: "Enduro", size: "L", build: "Race XT", price: 5499 , image: "https://store.pivotcycles.com/content/images/thumbs/0016340_switchblade.png", details: "The sequel to the Switchblade story heralds a new era of all mountain riding, with more travel, unrivaled versatility and progressive geometry. It unleashes dominance over enduro inspired descents, generates speed, and delivers the finesse needed for power moves on technical climbs. With a masterfully designed new dw-link shock layout, riders can optimize suspension performance like never before.")
Bike.create( manufacturer: "Pivot Cycles", model: "Switchblade", bike_type: "Enduro", size: "XL", build: "Race XT", price: 5499 , image: "https://store.pivotcycles.com/content/images/thumbs/0016340_switchblade.png", details: "The sequel to the Switchblade story heralds a new era of all mountain riding, with more travel, unrivaled versatility and progressive geometry. It unleashes dominance over enduro inspired descents, generates speed, and delivers the finesse needed for power moves on technical climbs. With a masterfully designed new dw-link shock layout, riders can optimize suspension performance like never before.")

Bike.create( manufacturer: "Pivot Cycles", model: "Trail 429", bike_type: "Trail", size: "S", build: "Race XT", price: 5099 , image: "https://store.pivotcycles.com/content/images/thumbs/0015991_trail-429.png", details: "What if you just want a bike that rips on nearly every trail? This is that bike. The Trail 429 is brilliant just about everywhere. It accelerates and climbs like a cross-country bike yet more than holds its own on tough terrain. ")
Bike.create( manufacturer: "Pivot Cycles", model: "Trail 429", bike_type: "Trail", size: "M", build: "Race XT", price: 5099 , image: "https://store.pivotcycles.com/content/images/thumbs/0015991_trail-429.png", details: "What if you just want a bike that rips on nearly every trail? This is that bike. The Trail 429 is brilliant just about everywhere. It accelerates and climbs like a cross-country bike yet more than holds its own on tough terrain. ")
Bike.create( manufacturer: "Pivot Cycles", model: "Trail 429", bike_type: "Trail", size: "L", build: "Race XT", price: 5099 , image: "https://store.pivotcycles.com/content/images/thumbs/0015991_trail-429.png", details: "What if you just want a bike that rips on nearly every trail? This is that bike. The Trail 429 is brilliant just about everywhere. It accelerates and climbs like a cross-country bike yet more than holds its own on tough terrain. ")
Bike.create( manufacturer: "Pivot Cycles", model: "Trail 429", bike_type: "Trail", size: "XL", build: "Race XT", price: 5099 , image: "https://store.pivotcycles.com/content/images/thumbs/0015991_trail-429.png", details: "What if you just want a bike that rips on nearly every trail? This is that bike. The Trail 429 is brilliant just about everywhere. It accelerates and climbs like a cross-country bike yet more than holds its own on tough terrain. ")

Bike.create( manufacturer: "Pivot Cycles", model: "LES SL", bike_type: "Cross Country", size: "S", build: "Race XT", price: 3999 , image: "https://store.pivotcycles.com/Content/Images/thumbs/00LSLV129ASXA--BLKMDSTDHN.png", details: "On the right course, nothing is faster than a hardtail, and nothing delivers the stiffness to weight ratio and raw speed as a Pivot LES SL. The LES SL is engineered to the Nth degree to deliver the kind of handling, extreme power transfer and weight that transforms every last watt of output into a race-winning performance.")
Bike.create( manufacturer: "Pivot Cycles", model: "LES SL", bike_type: "Cross Country", size: "M", build: "Race XT", price: 3999 , image: "https://store.pivotcycles.com/Content/Images/thumbs/00LSLV129ASXA--BLKMDSTDHN.png", details: "On the right course, nothing is faster than a hardtail, and nothing delivers the stiffness to weight ratio and raw speed as a Pivot LES SL. The LES SL is engineered to the Nth degree to deliver the kind of handling, extreme power transfer and weight that transforms every last watt of output into a race-winning performance.")
Bike.create( manufacturer: "Pivot Cycles", model: "LES SL", bike_type: "Cross Country", size: "L", build: "Race XT", price: 3999 , image: "https://store.pivotcycles.com/Content/Images/thumbs/00LSLV129ASXA--BLKMDSTDHN.png", details: "On the right course, nothing is faster than a hardtail, and nothing delivers the stiffness to weight ratio and raw speed as a Pivot LES SL. The LES SL is engineered to the Nth degree to deliver the kind of handling, extreme power transfer and weight that transforms every last watt of output into a race-winning performance.")
Bike.create( manufacturer: "Pivot Cycles", model: "LES SL", bike_type: "Cross Country", size: "XL", build: "Race XT", price: 3999 , image: "https://store.pivotcycles.com/Content/Images/thumbs/00LSLV129ASXA--BLKMDSTDHN.png", details: "On the right course, nothing is faster than a hardtail, and nothing delivers the stiffness to weight ratio and raw speed as a Pivot LES SL. The LES SL is engineered to the Nth degree to deliver the kind of handling, extreme power transfer and weight that transforms every last watt of output into a race-winning performance.")

Bike.create( manufacturer: "Pivot Cycles", model: "Vault", bike_type: "Gravel", size: "S", build: "Pro GRX", price: 5299 , image: "https://store.pivotcycles.com/content/images/thumbs/0018031_vault-v5.png", details: "The updated Pivot Vault breaks the only remaining gravel cycling speed record worth breaking; the Speed of Imagination. With unrivaled handling, massive tire clearance, and pro-caliber power transfer, your riding is limited only by the number of adventures you dream of.")
Bike.create( manufacturer: "Pivot Cycles", model: "Vault", bike_type: "Gravel", size: "M", build: "Pro GRX", price: 5299 , image: "https://store.pivotcycles.com/content/images/thumbs/0018031_vault-v5.png", details: "The updated Pivot Vault breaks the only remaining gravel cycling speed record worth breaking; the Speed of Imagination. With unrivaled handling, massive tire clearance, and pro-caliber power transfer, your riding is limited only by the number of adventures you dream of.")
Bike.create( manufacturer: "Pivot Cycles", model: "Vault", bike_type: "Gravel", size: "L", build: "Pro GRX", price: 5299 , image: "https://store.pivotcycles.com/content/images/thumbs/0018031_vault-v5.png", details: "The updated Pivot Vault breaks the only remaining gravel cycling speed record worth breaking; the Speed of Imagination. With unrivaled handling, massive tire clearance, and pro-caliber power transfer, your riding is limited only by the number of adventures you dream of.")
Bike.create( manufacturer: "Pivot Cycles", model: "Vault", bike_type: "Gravel", size: "XL", build: "Pro GRX", price: 5299 , image: "https://store.pivotcycles.com/content/images/thumbs/0018031_vault-v5.png", details: "The updated Pivot Vault breaks the only remaining gravel cycling speed record worth breaking; the Speed of Imagination. With unrivaled handling, massive tire clearance, and pro-caliber power transfer, your riding is limited only by the number of adventures you dream of.")

# Bike.create( manufacturer: "", model: "", bike_type: "Downhill", size: "S", build: "", price: , image: "", details: "")
# Bike.create( manufacturer: "", model: "", bike_type: "Downhill", size: "M", build: "", price: , image: "", details: "")
# Bike.create( manufacturer: "", model: "", bike_type: "Downhill", size: "L", build: "", price: , image: "", details: "")
# Bike.create( manufacturer: "", model: "", bike_type: "Downhill", size: "XL", build: "", price: , image: "", details: "")

# Bike.create( manufacturer: "", model: "", bike_type: "Enduro", size: "S", build: "", price: , image: "", details: "")
# Bike.create( manufacturer: "", model: "", bike_type: "Enduro", size: "M", build: "", price: , image: "", details: "")
# Bike.create( manufacturer: "", model: "", bike_type: "Enduro", size: "L", build: "", price: , image: "", details: "")
# Bike.create( manufacturer: "", model: "", bike_type: "Enduro", size: "XL", build: "", price: , image: "", details: "")

# Bike.create( manufacturer: "", model: "", bike_type: "Trail", size: "S", build: "", price: , image: "", details: "")
# Bike.create( manufacturer: "", model: "", bike_type: "Trail", size: "M", build: "", price: , image: "", details: "")
# Bike.create( manufacturer: "", model: "", bike_type: "Trail", size: "L", build: "", price: , image: "", details: "")
# Bike.create( manufacturer: "", model: "", bike_type: "Trail", size: "XL", build: "", price: , image: "", details: "")

# Bike.create( manufacturer: "", model: "", bike_type: "Cross Country", size: "S", build: "", price: , image: "", details: "")
# Bike.create( manufacturer: "", model: "", bike_type: "Cross Country", size: "M", build: "", price: , image: "", details: "")
# Bike.create( manufacturer: "", model: "", bike_type: "Cross Country", size: "L", build: "", price: , image: "", details: "")
# Bike.create( manufacturer: "", model: "", bike_type: "Cross Country", size: "XL", build: "", price: , image: "", details: "")

# Bike.create( manufacturer: "", model: "", bike_type: "Gravel", size: "S", build: "", price: , image: "", details: "")
# Bike.create( manufacturer: "", model: "", bike_type: "Gravel", size: "M", build: "", price: , image: "", details: "")
# Bike.create( manufacturer: "", model: "", bike_type: "Gravel", size: "L", build: "", price: , image: "", details: "")
# Bike.create( manufacturer: "", model: "", bike_type: "Gravel", size: "XL", build: "", price: , image: "", details: "")

