# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rails db:seed command (or created alongside the database with db:setup).
#
# Examples:
#
#   movies = Movie.create([{ name: 'Star Wars' }, { name: 'Lord of the Rings' }])
#   Character.create(name: 'Luke', movie: movies.first)

dan = User.create(username: "dan", name: "Daniel Cole", email:"dantheman@gmail.com", password: "daniel", password_confirmation: "daniel")
will = User.create(username: "will", name: "William Stewart", email:"willshred4lyfe@gmail.com", password: "william", password_confirmation: "william")
sam = User.create(username: "sam", name: "Samuel Moseley", email:"trailsammich@gmail.com", password: "samuel", password_confirmation: "samuel")
# Bike.create( manufacturer: "", model: "", bike_type: "", size: "", build: "", price: , image: "", details: "")

Bike.create( manufacturer: "Specialized", model: "Epic", bike_type: "Cross Country", size: "S", build: "Pro 29", price: 7925 , image: "https://s7d5.scene7.com/is/image/Specialized/?layer=0&wid=1920&hei=640&fmt=jpg&src=is{Specialized/pdp-product-bg-dark-fb?wid=1920&hei=640}&layer=1&src=is{Specialized/97620-10_EPIC-PRO-ABLN-BLK_HERO?wid=1920&hei=640&$hybris-pdp-hero-exp$}", details: "What do you get when you open up the taps on trickle-down technology? That'd be the Epic Pro. A waterfall of performance coming straight down from Mount S-Works, the Epic Pro benefits from the most efficient suspension design we've ever created, not to mention a frame that's as light as the previous-generation S-Works while offering the same incredibly efficient power transfer of the current cream of the World Cup crop.")
Bike.create( manufacturer: "Specialized", model: "Epic Hardtail", bike_type: "Cross Country", size: "S", build: "Pro", price: 5520, image: "https://s7d5.scene7.com/is/image/Specialized/?$hybris-hd$&layer=0&fmt=jpg&src=is{Specialized/pdp-product-bg-dark-zoom?$hybris-hd$}&layer=1&src=is{Specialized/91320-10_EPIC-HT-PRO-CARBON-29-VIVPNK-PROBLU-METWHTSIL_HERO?$hybris-hd$}", details: "If you ask us, it's been too long since hardtails got their world shaken up. Well, our all-new Epic Hardtail Pro Carbon does just that. New geometry, crazy-low frame weight, and a build from the racing gods—this bike is ready to shatter the mold.")
Bike.create( manufacturer: "Specialized", model: "Stumpjumper", bike_type: "Trail", size: "S", build: "Evo PRO 29", price: 5296 , image: "https://s7d5.scene7.com/is/image/Specialized/?$hybris-hd$&layer=0&fmt=jpg&src=is{Specialized/pdp-product-bg-dark-zoom?$hybris-hd$}&layer=1&src=is{Specialized/93319-11_SJ-FSR-MEN-PRO-CARBON-EVO-29-CARB-MNT_HERO?$hybris-hd$}", details: "If you're looking for a traditional trail bike, you've come to the wrong place. Pack your stuff, say your goodbyes, and get out. But if you're on the hunt for the perfect shred sled—you know, a trail bike that you can take down DH trails, huck off blind drops, or plow through the rowdiest of rock gardens—you'll find yourself right at home on the Stumpjumper EVO Pro 29.")
Bike.create( manufacturer: "Specialized", model: "Enduro", bike_type: "Enduro", size: "S", build: "S-Works", price: 9750 , image: "https://s7d5.scene7.com/is/image/Specialized/?$hybris-hd$&layer=0&fmt=jpg&src=is{Specialized/pdp-product-bg-dark-zoom?$hybris-hd$}&layer=1&src=is{Specialized/93620-00_ENDURO-SW-CARBON-29-BLKTNT-BRSHBLKCP-CARB_HERO?$hybris-hd$}", details: "This is the bike that defines the very genre that bears its name. The S-Works Enduro features a bomber-yet-lightweight carbon frame that blissfully tackles the kind of terrain that chews up and spits out lesser bikes. And it's absolutely dressed to kill. Let the drooling begin.")
Bike.create( manufacturer: "Specialized", model: "Demo", bike_type: "Downhill", size: "S", build: "Race 29", price: 6500 , image: "https://s7d5.scene7.com/is/image/Specialized/?$hybris-hd$&layer=0&fmt=jpg&src=is{Specialized/pdp-product-bg-dark-zoom?$hybris-hd$}&layer=1&src=is{Specialized/94519-00_DEMO_RACE-29_METBLK-BNTYEL_HERO?$hybris-hd$}", details: "The new Demo 29 comes roaring comes roaring out of the gates with multiple World Cup wins already under its belt. New chassis, new suspension kinematics, new geometry, and, yeah, new wheel size. We’ve hung the Race model with the best gravity kit available. Full gas. Full fast.")
Bike.create( manufacturer: "Specialized", model: "Diverge", bike_type: "Gravel", size: "S", build: "Pro Carbon", price: 6700 , image: "https://s7d5.scene7.com/is/image/Specialized/?$hybris-hd$&layer=0&fmt=jpg&src=is{Specialized/pdp-product-bg-dark-zoom?$hybris-hd$}&layer=1&src=is{Specialized/96220-10_DIVERGE-PRO-CARBON-ETAP-REDWD-SMK-CHRM_HERO?$hybris-hd$}", details: "Whether your goal is to escape on gravel back roads, far from cars and crowds, or drop the hammer at the front of your favorite gravel race, no bike does it better than the new Diverge. It’s quite simply the fastest, most capable - and just maybe the most fun - bike we’ve ever made, delivering a ride that’s quick and lively under power, but stable and confidence inspiring when the terrain gets rough.")

Bike.create( manufacturer: "Specialized", model: "Epic", bike_type: "Cross Country", size: "M", build: "Pro 29", price: 7925 , image: "https://s7d5.scene7.com/is/image/Specialized/?layer=0&wid=1920&hei=640&fmt=jpg&src=is{Specialized/pdp-product-bg-dark-fb?wid=1920&hei=640}&layer=1&src=is{Specialized/97620-10_EPIC-PRO-ABLN-BLK_HERO?wid=1920&hei=640&$hybris-pdp-hero-exp$}", details: "What do you get when you open up the taps on trickle-down technology? That'd be the Epic Pro. A waterfall of performance coming straight down from Mount S-Works, the Epic Pro benefits from the most efficient suspension design we've ever created, not to mention a frame that's as light as the previous-generation S-Works while offering the same incredibly efficient power transfer of the current cream of the World Cup crop.")
Bike.create( manufacturer: "Specialized", model: "Epic Hardtail", bike_type: "Cross Country", size: "S", build: "Pro", price: 5520, image: "https://s7d5.scene7.com/is/image/Specialized/?$hybris-hd$&layer=0&fmt=jpg&src=is{Specialized/pdp-product-bg-dark-zoom?$hybris-hd$}&layer=1&src=is{Specialized/91320-10_EPIC-HT-PRO-CARBON-29-VIVPNK-PROBLU-METWHTSIL_HERO?$hybris-hd$}", details: "If you ask us, it's been too long since hardtails got their world shaken up. Well, our all-new Epic Hardtail Pro Carbon does just that. New geometry, crazy-low frame weight, and a build from the racing gods—this bike is ready to shatter the mold.")
Bike.create( manufacturer: "Specialized", model: "Stumpjumper", bike_type: "Trail", size: "M", build: "Evo PRO 29", price: 5296 , image: "https://s7d5.scene7.com/is/image/Specialized/?$hybris-hd$&layer=0&fmt=jpg&src=is{Specialized/pdp-product-bg-dark-zoom?$hybris-hd$}&layer=1&src=is{Specialized/93319-11_SJ-FSR-MEN-PRO-CARBON-EVO-29-CARB-MNT_HERO?$hybris-hd$}", details: "If you're looking for a traditional trail bike, you've come to the wrong place. Pack your stuff, say your goodbyes, and get out. But if you're on the hunt for the perfect shred sled—you know, a trail bike that you can take down DH trails, huck off blind drops, or plow through the rowdiest of rock gardens—you'll find yourself right at home on the Stumpjumper EVO Pro 29.")
Bike.create( manufacturer: "Specialized", model: "Enduro", bike_type: "Enduro", size: "M", build: "S-Works", price: 9750 , image: "https://s7d5.scene7.com/is/image/Specialized/?$hybris-hd$&layer=0&fmt=jpg&src=is{Specialized/pdp-product-bg-dark-zoom?$hybris-hd$}&layer=1&src=is{Specialized/93620-00_ENDURO-SW-CARBON-29-BLKTNT-BRSHBLKCP-CARB_HERO?$hybris-hd$}", details: "This is the bike that defines the very genre that bears its name. The S-Works Enduro features a bomber-yet-lightweight carbon frame that blissfully tackles the kind of terrain that chews up and spits out lesser bikes. And it's absolutely dressed to kill. Let the drooling begin.")
Bike.create( manufacturer: "Specialized", model: "Demo", bike_type: "Downhill", size: "M", build: "Race 29", price: 6500 , image: "https://s7d5.scene7.com/is/image/Specialized/?$hybris-hd$&layer=0&fmt=jpg&src=is{Specialized/pdp-product-bg-dark-zoom?$hybris-hd$}&layer=1&src=is{Specialized/94519-00_DEMO_RACE-29_METBLK-BNTYEL_HERO?$hybris-hd$}", details: "The new Demo 29 comes roaring comes roaring out of the gates with multiple World Cup wins already under its belt. New chassis, new suspension kinematics, new geometry, and, yeah, new wheel size. We’ve hung the Race model with the best gravity kit available. Full gas. Full fast.")
Bike.create( manufacturer: "Specialized", model: "Diverge", bike_type: "Gravel", size: "M", build: "Pro Carbon", price: 6700 , image: "https://s7d5.scene7.com/is/image/Specialized/?$hybris-hd$&layer=0&fmt=jpg&src=is{Specialized/pdp-product-bg-dark-zoom?$hybris-hd$}&layer=1&src=is{Specialized/96220-10_DIVERGE-PRO-CARBON-ETAP-REDWD-SMK-CHRM_HERO?$hybris-hd$}", details: "Whether your goal is to escape on gravel back roads, far from cars and crowds, or drop the hammer at the front of your favorite gravel race, no bike does it better than the new Diverge. It’s quite simply the fastest, most capable - and just maybe the most fun - bike we’ve ever made, delivering a ride that’s quick and lively under power, but stable and confidence inspiring when the terrain gets rough.")

Bike.create( manufacturer: "Specialized", model: "Epic", bike_type: "Cross Country", size: "L", build: "Pro 29", price: 7925 , image: "https://s7d5.scene7.com/is/image/Specialized/?layer=0&wid=1920&hei=640&fmt=jpg&src=is{Specialized/pdp-product-bg-dark-fb?wid=1920&hei=640}&layer=1&src=is{Specialized/97620-10_EPIC-PRO-ABLN-BLK_HERO?wid=1920&hei=640&$hybris-pdp-hero-exp$}", details: "What do you get when you open up the taps on trickle-down technology? That'd be the Epic Pro. A waterfall of performance coming straight down from Mount S-Works, the Epic Pro benefits from the most efficient suspension design we've ever created, not to mention a frame that's as light as the previous-generation S-Works while offering the same incredibly efficient power transfer of the current cream of the World Cup crop.")
Bike.create( manufacturer: "Specialized", model: "Epic Hardtail", bike_type: "Cross Country", size: "L", build: "Pro", price: 5520, image: "https://s7d5.scene7.com/is/image/Specialized/?$hybris-hd$&layer=0&fmt=jpg&src=is{Specialized/pdp-product-bg-dark-zoom?$hybris-hd$}&layer=1&src=is{Specialized/91320-10_EPIC-HT-PRO-CARBON-29-VIVPNK-PROBLU-METWHTSIL_HERO?$hybris-hd$}", details: "If you ask us, it's been too long since hardtails got their world shaken up. Well, our all-new Epic Hardtail Pro Carbon does just that. New geometry, crazy-low frame weight, and a build from the racing gods—this bike is ready to shatter the mold.")
Bike.create( manufacturer: "Specialized", model: "Stumpjumper", bike_type: "Trail", size: "L", build: "Evo PRO 29", price: 5296 , image: "https://s7d5.scene7.com/is/image/Specialized/?$hybris-hd$&layer=0&fmt=jpg&src=is{Specialized/pdp-product-bg-dark-zoom?$hybris-hd$}&layer=1&src=is{Specialized/93319-11_SJ-FSR-MEN-PRO-CARBON-EVO-29-CARB-MNT_HERO?$hybris-hd$}", details: "If you're looking for a traditional trail bike, you've come to the wrong place. Pack your stuff, say your goodbyes, and get out. But if you're on the hunt for the perfect shred sled—you know, a trail bike that you can take down DH trails, huck off blind drops, or plow through the rowdiest of rock gardens—you'll find yourself right at home on the Stumpjumper EVO Pro 29.")
Bike.create( manufacturer: "Specialized", model: "Enduro", bike_type: "Enduro", size: "L", build: "S-Works", price: 9750 , image: "https://s7d5.scene7.com/is/image/Specialized/?$hybris-hd$&layer=0&fmt=jpg&src=is{Specialized/pdp-product-bg-dark-zoom?$hybris-hd$}&layer=1&src=is{Specialized/93620-00_ENDURO-SW-CARBON-29-BLKTNT-BRSHBLKCP-CARB_HERO?$hybris-hd$}", details: "This is the bike that defines the very genre that bears its name. The S-Works Enduro features a bomber-yet-lightweight carbon frame that blissfully tackles the kind of terrain that chews up and spits out lesser bikes. And it's absolutely dressed to kill. Let the drooling begin.")
Bike.create( manufacturer: "Specialized", model: "Demo", bike_type: "Downhill", size: "L", build: "Race 29", price: 6500 , image: "https://s7d5.scene7.com/is/image/Specialized/?$hybris-hd$&layer=0&fmt=jpg&src=is{Specialized/pdp-product-bg-dark-zoom?$hybris-hd$}&layer=1&src=is{Specialized/94519-00_DEMO_RACE-29_METBLK-BNTYEL_HERO?$hybris-hd$}", details: "The new Demo 29 comes roaring comes roaring out of the gates with multiple World Cup wins already under its belt. New chassis, new suspension kinematics, new geometry, and, yeah, new wheel size. We’ve hung the Race model with the best gravity kit available. Full gas. Full fast.")
Bike.create( manufacturer: "Specialized", model: "Diverge", bike_type: "Gravel", size: "L", build: "Pro Carbon", price: 6700 , image: "https://s7d5.scene7.com/is/image/Specialized/?$hybris-hd$&layer=0&fmt=jpg&src=is{Specialized/pdp-product-bg-dark-zoom?$hybris-hd$}&layer=1&src=is{Specialized/96220-10_DIVERGE-PRO-CARBON-ETAP-REDWD-SMK-CHRM_HERO?$hybris-hd$}", details: "Whether your goal is to escape on gravel back roads, far from cars and crowds, or drop the hammer at the front of your favorite gravel race, no bike does it better than the new Diverge. It’s quite simply the fastest, most capable - and just maybe the most fun - bike we’ve ever made, delivering a ride that’s quick and lively under power, but stable and confidence inspiring when the terrain gets rough.")

Bike.create( manufacturer: "Specialized", model: "Epic", bike_type: "Cross Country", size: "XL", build: "Pro 29", price: 7925 , image: "https://s7d5.scene7.com/is/image/Specialized/?layer=0&wid=1920&hei=640&fmt=jpg&src=is{Specialized/pdp-product-bg-dark-fb?wid=1920&hei=640}&layer=1&src=is{Specialized/97620-10_EPIC-PRO-ABLN-BLK_HERO?wid=1920&hei=640&$hybris-pdp-hero-exp$}", details: "What do you get when you open up the taps on trickle-down technology? That'd be the Epic Pro. A waterfall of performance coming straight down from Mount S-Works, the Epic Pro benefits from the most efficient suspension design we've ever created, not to mention a frame that's as light as the previous-generation S-Works while offering the same incredibly efficient power transfer of the current cream of the World Cup crop.")
Bike.create( manufacturer: "Specialized", model: "Epic Hardtail", bike_type: "Cross Country", size: "XL", build: "Pro", price: 5520, image: "https://s7d5.scene7.com/is/image/Specialized/?$hybris-hd$&layer=0&fmt=jpg&src=is{Specialized/pdp-product-bg-dark-zoom?$hybris-hd$}&layer=1&src=is{Specialized/91320-10_EPIC-HT-PRO-CARBON-29-VIVPNK-PROBLU-METWHTSIL_HERO?$hybris-hd$}", details: "If you ask us, it's been too long since hardtails got their world shaken up. Well, our all-new Epic Hardtail Pro Carbon does just that. New geometry, crazy-low frame weight, and a build from the racing gods—this bike is ready to shatter the mold.")
Bike.create( manufacturer: "Specialized", model: "Stumpjumper", bike_type: "Trail", size: "XL", build: "Evo PRO 29", price: 5296 , image: "https://s7d5.scene7.com/is/image/Specialized/?$hybris-hd$&layer=0&fmt=jpg&src=is{Specialized/pdp-product-bg-dark-zoom?$hybris-hd$}&layer=1&src=is{Specialized/93319-11_SJ-FSR-MEN-PRO-CARBON-EVO-29-CARB-MNT_HERO?$hybris-hd$}", details: "If you're looking for a traditional trail bike, you've come to the wrong place. Pack your stuff, say your goodbyes, and get out. But if you're on the hunt for the perfect shred sled—you know, a trail bike that you can take down DH trails, huck off blind drops, or plow through the rowdiest of rock gardens—you'll find yourself right at home on the Stumpjumper EVO Pro 29.")
Bike.create( manufacturer: "Specialized", model: "Enduro", bike_type: "Enduro", size: "L", build: "S-Works", price: 9750 , image: "https://s7d5.scene7.com/is/image/Specialized/?$hybris-hd$&layer=0&fmt=jpg&src=is{Specialized/pdp-product-bg-dark-zoom?$hybris-hd$}&layer=1&src=is{Specialized/93620-00_ENDURO-SW-CARBON-29-BLKTNT-BRSHBLKCP-CARB_HERO?$hybris-hd$}", details: "This is the bike that defines the very genre that bears its name. The S-Works Enduro features a bomber-yet-lightweight carbon frame that blissfully tackles the kind of terrain that chews up and spits out lesser bikes. And it's absolutely dressed to kill. Let the drooling begin.")
Bike.create( manufacturer: "Specialized", model: "Demo", bike_type: "Downhill", size: "XL", build: "Race 29", price: 6500 , image: "https://s7d5.scene7.com/is/image/Specialized/?$hybris-hd$&layer=0&fmt=jpg&src=is{Specialized/pdp-product-bg-dark-zoom?$hybris-hd$}&layer=1&src=is{Specialized/94519-00_DEMO_RACE-29_METBLK-BNTYEL_HERO?$hybris-hd$}", details: "The new Demo 29 comes roaring comes roaring out of the gates with multiple World Cup wins already under its belt. New chassis, new suspension kinematics, new geometry, and, yeah, new wheel size. We’ve hung the Race model with the best gravity kit available. Full gas. Full fast.")
Bike.create( manufacturer: "Specialized", model: "Diverge", bike_type: "Gravel", size: "XL", build: "Pro Carbon", price: 6700 , image: "https://s7d5.scene7.com/is/image/Specialized/?$hybris-hd$&layer=0&fmt=jpg&src=is{Specialized/pdp-product-bg-dark-zoom?$hybris-hd$}&layer=1&src=is{Specialized/96220-10_DIVERGE-PRO-CARBON-ETAP-REDWD-SMK-CHRM_HERO?$hybris-hd$}", details: "Whether your goal is to escape on gravel back roads, far from cars and crowds, or drop the hammer at the front of your favorite gravel race, no bike does it better than the new Diverge. It’s quite simply the fastest, most capable - and just maybe the most fun - bike we’ve ever made, delivering a ride that’s quick and lively under power, but stable and confidence inspiring when the terrain gets rough.")


Bike.create( manufacturer: "Santa Cruz", model: "Blur", bike_type: "Cross Country", size: "S", build: "Carbon CC - X01 - 29", price: 7699 , image: "https://www.santacruzbicycles.com/files/styles/scb_natural_2000_auto/public/hero/my21_hero_blur_black.jpg?itok=c3bIFnAQ", details: "The Blur is our ride fast, ride far, ride-harder-than-your-heart-can-take XC race bike.")
Bike.create( manufacturer: "Santa Cruz", model: "5010", bike_type: "Trail", size: "S", build: "Carbon CC - X01 - 27.5", price: 8099, image: "https://www.santacruzbicycles.com/files/styles/scb_natural_2000_auto/public/hero/my21_hero_5010_blue.jpg?itok=vO9hFHbj", details: "The 5010 turns obstacles into features. Its nimble, poppy feel makes even the most mundane rides feel like they're loaded with features to hop, skip and jump over. It's the kind of bike that makes new trails feel as familiar as the back of your hand.")
Bike.create( manufacturer: "Santa Cruz", model: "Bronson", bike_type: "Enduro", size: "S", build: "Carbon CC - X01 - 27.5", price: 8299, image: "https://www.santacruzbicycles.com/files/styles/scb_natural_2000_auto/public/hero/my21_hero_bronson_green.jpg?itok=h2nTgVbG", details: "Santa Cruz's most notorious thriller, the Bronson, is ready for action no matter what role it's cast into. The Bronson has the biggest personality in our range. From flat out on the trail to fully flat over a table, each new generation redefines expectations of what a 150mm bike can do.")
Bike.create( manufacturer: "Santa Cruz", model: "V-10", bike_type: "Downhill", size: "S", build: "Carbon CC - X01 - 27.5", price: 7999, image: "https://www.santacruzbicycles.com/files/styles/scb_natural_2000_auto/public/hero/my21_hero_v10_mx.jpg?itok=dWA3411A", details: "The V10 is designed to be exactly the right bike for anyone who steps up to the startline with eyes on a podium. The racer who chooses a V10 is the recipient of every bit of work and puzzling that’s gone into the Syndicate’s race bikes.")
Bike.create( manufacturer: "Santa Cruz", model: "Stigmata", bike_type: "Gravel", size: "S", build: "Carbon CC - Force 1X - 700c", price: 6699, image: "https://www.santacruzbicycles.com/files/styles/scb_natural_2000_auto/public/hero/my21_hero_stig_green.jpg?itok=d1HO2YC6", details: "When the Stigmata was resurrected in 2015, we fused a number of MTB standards and design features to create our spin on the modern CX bike. Something must have clicked, because within months of launch it raced to victory at the legendary Three Peaks, and has continued to contend at elite cyclocross races around the world.")

Bike.create( manufacturer: "Santa Cruz", model: "Blur", bike_type: "Cross Country", size: "M", build: "Carbon CC - X01 - 29", price: 7699 , image: "https://www.santacruzbicycles.com/files/styles/scb_natural_2000_auto/public/hero/my21_hero_blur_black.jpg?itok=c3bIFnAQ", details: "The Blur is our ride fast, ride far, ride-harder-than-your-heart-can-take XC race bike.")
Bike.create( manufacturer: "Santa Cruz", model: "5010", bike_type: "Trail", size: "M", build: "Carbon CC - X01 - 27.5", price: 8099, image: "https://www.santacruzbicycles.com/files/styles/scb_natural_2000_auto/public/hero/my21_hero_5010_blue.jpg?itok=vO9hFHbj", details: "The 5010 turns obstacles into features. Its nimble, poppy feel makes even the most mundane rides feel like they're loaded with features to hop, skip and jump over. It's the kind of bike that makes new trails feel as familiar as the back of your hand.")
Bike.create( manufacturer: "Santa Cruz", model: "Bronson", bike_type: "Enduro", size: "M", build: "Carbon CC - X01 - 27.5", price: 8299, image: "https://www.santacruzbicycles.com/files/styles/scb_natural_2000_auto/public/hero/my21_hero_bronson_green.jpg?itok=h2nTgVbG", details: "Santa Cruz's most notorious thriller, the Bronson, is ready for action no matter what role it's cast into. The Bronson has the biggest personality in our range. From flat out on the trail to fully flat over a table, each new generation redefines expectations of what a 150mm bike can do.")
Bike.create( manufacturer: "Santa Cruz", model: "V-10", bike_type: "Downhill", size: "M", build: "Carbon CC - X01 - 27.5", price: 7999, image: "https://www.santacruzbicycles.com/files/styles/scb_natural_2000_auto/public/hero/my21_hero_v10_mx.jpg?itok=dWA3411A", details: "The V10 is designed to be exactly the right bike for anyone who steps up to the startline with eyes on a podium. The racer who chooses a V10 is the recipient of every bit of work and puzzling that’s gone into the Syndicate’s race bikes.")
Bike.create( manufacturer: "Santa Cruz", model: "Stigmata", bike_type: "Gravel", size: "M", build: "Carbon CC - Force 1X - 700c", price: 6699, image: "https://www.santacruzbicycles.com/files/styles/scb_natural_2000_auto/public/hero/my21_hero_stig_green.jpg?itok=d1HO2YC6", details: "When the Stigmata was resurrected in 2015, we fused a number of MTB standards and design features to create our spin on the modern CX bike. Something must have clicked, because within months of launch it raced to victory at the legendary Three Peaks, and has continued to contend at elite cyclocross races around the world.")

Bike.create( manufacturer: "Santa Cruz", model: "Blur", bike_type: "Cross Country", size: "L", build: "Carbon CC - X01 - 29", price: 7699 , image: "https://www.santacruzbicycles.com/files/styles/scb_natural_2000_auto/public/hero/my21_hero_blur_black.jpg?itok=c3bIFnAQ", details: "The Blur is our ride fast, ride far, ride-harder-than-your-heart-can-take XC race bike.")
Bike.create( manufacturer: "Santa Cruz", model: "5010", bike_type: "Trail", size: "L", build: "Carbon CC - X01 - 27.5", price: 8099, image: "https://www.santacruzbicycles.com/files/styles/scb_natural_2000_auto/public/hero/my21_hero_5010_blue.jpg?itok=vO9hFHbj", details: "The 5010 turns obstacles into features. Its nimble, poppy feel makes even the most mundane rides feel like they're loaded with features to hop, skip and jump over. It's the kind of bike that makes new trails feel as familiar as the back of your hand.")
bronsonL = Bike.create( manufacturer: "Santa Cruz", model: "Bronson", bike_type: "Enduro", size: "L", build: "Carbon CC - X01 - 27.5", price: 8299, image: "https://www.santacruzbicycles.com/files/styles/scb_natural_2000_auto/public/hero/my21_hero_bronson_green.jpg?itok=h2nTgVbG", details: "Santa Cruz's most notorious thriller, the Bronson, is ready for action no matter what role it's cast into. The Bronson has the biggest personality in our range. From flat out on the trail to fully flat over a table, each new generation redefines expectations of what a 150mm bike can do.")
veetenL = Bike.create( manufacturer: "Santa Cruz", model: "V-10", bike_type: "Downhill", size: "L", build: "Carbon CC - X01 - 27.5", price: 7999, image: "https://www.santacruzbicycles.com/files/styles/scb_natural_2000_auto/public/hero/my21_hero_v10_mx.jpg?itok=dWA3411A", details: "The V10 is designed to be exactly the right bike for anyone who steps up to the startline with eyes on a podium. The racer who chooses a V10 is the recipient of every bit of work and puzzling that’s gone into the Syndicate’s race bikes.")
stigmataL = Bike.create( manufacturer: "Santa Cruz", model: "Stigmata", bike_type: "Gravel", size: "L", build: "Carbon CC - Force 1X - 700c", price: 6699, image: "https://www.santacruzbicycles.com/files/styles/scb_natural_2000_auto/public/hero/my21_hero_stig_green.jpg?itok=d1HO2YC6", details: "When the Stigmata was resurrected in 2015, we fused a number of MTB standards and design features to create our spin on the modern CX bike. Something must have clicked, because within months of launch it raced to victory at the legendary Three Peaks, and has continued to contend at elite cyclocross races around the world.")

Bike.create( manufacturer: "Santa Cruz", model: "Blur", bike_type: "Cross Country", size: "XL", build: "Carbon CC - X01 - 29", price: 7699 , image: "https://www.santacruzbicycles.com/files/styles/scb_natural_2000_auto/public/hero/my21_hero_blur_black.jpg?itok=c3bIFnAQ", details: "The Blur is our ride fast, ride far, ride-harder-than-your-heart-can-take XC race bike.")
Bike.create( manufacturer: "Santa Cruz", model: "5010", bike_type: "Trail", size: "XL", build: "Carbon CC - X01 - 27.5", price: 8099, image: "https://www.santacruzbicycles.com/files/styles/scb_natural_2000_auto/public/hero/my21_hero_5010_blue.jpg?itok=vO9hFHbj", details: "The 5010 turns obstacles into features. Its nimble, poppy feel makes even the most mundane rides feel like they're loaded with features to hop, skip and jump over. It's the kind of bike that makes new trails feel as familiar as the back of your hand.")
Bike.create( manufacturer: "Santa Cruz", model: "Bronson", bike_type: "Enduro", size: "XL", build: "Carbon CC - X01 - 27.5", price: 8299, image: "https://www.santacruzbicycles.com/files/styles/scb_natural_2000_auto/public/hero/my21_hero_bronson_green.jpg?itok=h2nTgVbG", details: "Santa Cruz's most notorious thriller, the Bronson, is ready for action no matter what role it's cast into. The Bronson has the biggest personality in our range. From flat out on the trail to fully flat over a table, each new generation redefines expectations of what a 150mm bike can do.")
veetenXL = Bike.create( manufacturer: "Santa Cruz", model: "V-10", bike_type: "Downhill", size: "XL", build: "Carbon CC - X01 - 27.5", price: 7999, image: "https://www.santacruzbicycles.com/files/styles/scb_natural_2000_auto/public/hero/my21_hero_v10_mx.jpg?itok=dWA3411A", details: "The V10 is designed to be exactly the right bike for anyone who steps up to the startline with eyes on a podium. The racer who chooses a V10 is the recipient of every bit of work and puzzling that’s gone into the Syndicate’s race bikes.")
Bike.create( manufacturer: "Santa Cruz", model: "Stigmata", bike_type: "Gravel", size: "XL", build: "Carbon CC - Force 1X - 700c", price: 6699, image: "https://www.santacruzbicycles.com/files/styles/scb_natural_2000_auto/public/hero/my21_hero_stig_green.jpg?itok=d1HO2YC6", details: "When the Stigmata was resurrected in 2015, we fused a number of MTB standards and design features to create our spin on the modern CX bike. Something must have clicked, because within months of launch it raced to victory at the legendary Three Peaks, and has continued to contend at elite cyclocross races around the world.")

o1 = Order.create(user_id: dan.id, order_total: 16298)
o2 = Order.create(user_id: dan.id, order_total: 6699)
o3 = Order.create(user_id: will.id, order_total: 7999)
o1.bikes << bronsonL
o1.bikes << veetenL
o2.bikes << stigmataL
o3.bikes << veetenXL